// ─── Portal Changelog ─────────────────────────────────────────────────────────
// Each entry represents a named release. Add new entries to the TOP of the
// array so the most recent version appears first in the UI.

export type ChangeCategory =
  | 'Cases'
  | 'Returns'
  | 'Refunds'
  | 'Orders'
  | 'Inventory'
  | 'Promotions'
  | 'Replenishment'
  | 'Roster'
  | 'Dashboard'
  | 'Performance'
  | 'Security'
  | 'Admin'
  | 'UI/UX';

export type ChangeEntry = {
  category: ChangeCategory;
  text: string;
};

export type ChangelogVersion = {
  version: string;       // e.g. "v1.8"
  label: string;         // e.g. "UI Polish"
  date: string;          // ISO date string  "2026-05-03"
  summary: string;       // One-sentence description shown in the card header
  changes: ChangeEntry[];
  isLatest?: boolean;
};

export const CHANGELOG: ChangelogVersion[] = [
  {
    version: 'v7.7',
    label: 'Team View Preview',
    date: '2026-05-20',
    isLatest: true,
    summary: 'Admins can now preview the portal as a team member to check the dashboard and available tabs.',
    changes: [
      { category: 'UI/UX', text: 'Admins now have a View as team toggle in the sidebar footer.' },
      { category: 'Dashboard', text: 'Team view preview switches the dashboard to the team-member layout without changing the admin account permissions.' },
      { category: 'Security', text: 'The preview only changes local UI visibility; actual admin access remains unchanged and can be restored instantly.' },
    ],
  },
  {
    version: 'v7.6',
    label: 'Team Inventory Visibility',
    date: '2026-05-20',
    isLatest: false,
    summary: 'Team members can now see Incoming Shipments and Restock Tracker without needing full admin inventory access.',
    changes: [
      { category: 'Inventory', text: 'Incoming Shipments now appears in the Inventory navigation for team members.' },
      { category: 'Inventory', text: 'Restock Tracker now appears in the Inventory navigation for team members while Stock Room remains admin-only.' },
      { category: 'Security', text: 'Route access now allows /stock/restock for team members without opening the main Stock Room page.' },
    ],
  },
  {
    version: 'v7.5',
    label: 'Return Logged By Fix',
    date: '2026-05-20',
    isLatest: false,
    summary: 'Return requests now reliably record the logged-in staff member and let missing names be repaired from the edit drawer.',
    changes: [
      { category: 'Returns', text: 'Log Return Request now fills Logged By from the active portal login even if the user profile finishes loading after the drawer opens.' },
      { category: 'Returns', text: 'Editing a return request with a missing Logged By value now backfills the current staff member for non-admin users, while admins can still select the correct staff member.' },
      { category: 'Security', text: 'The returns API now falls back to the signed-in session name when a request is saved without a Logged By value.' },
    ],
  },
  {
    version: 'v7.4',
    label: 'Login Session Refresh',
    date: '2026-05-20',
    isLatest: false,
    summary: 'Portal login now refreshes the active session immediately so names and admin access appear without a manual browser refresh.',
    changes: [
      { category: 'Security', text: 'The auth provider now re-checks the current session after navigation so the sidebar picks up the logged-in user and role reliably.' },
      { category: 'UI/UX', text: 'Signing in now performs a clean handoff into the portal, preventing the sidebar from staying on Loading or showing staff-only navigation for admins.' },
    ],
  },
  {
    version: 'v7.3',
    label: 'Replenishment Tracking Edits',
    date: '2026-05-19',
    isLatest: false,
    summary: 'Dispatched replenishment tracking details can now be corrected from the order detail page.',
    changes: [
      { category: 'Replenishment', text: 'Fixed the 3PL dispatch card edit action so existing tracking numbers switch into an editable form instead of staying as a link.' },
      { category: 'Replenishment', text: '3PL tracking reference and dispatch date can now both be corrected after dispatch.' },
      { category: 'UI/UX', text: 'The inline edit state now has clear Save and Cancel controls for fixing dispatch details quickly.' },
    ],
  },
  {
    version: 'v7.2',
    label: 'Slack Replenishment Import',
    date: '2026-05-18',
    isLatest: false,
    summary: 'Replenishment requests can now be imported from pasted Slack request text and split between Stock Room and 3PL automatically.',
    changes: [
      { category: 'Replenishment', text: 'Added Smart import from Slack to the New Replenishment Request modal for parsing SKU send quantities from pasted or dropped Slack text.' },
      { category: 'Replenishment', text: 'Imported lines now match against Stock Room SKUs, use available office stock first, and create 3PL lines for any shortfall.' },
      { category: 'UI/UX', text: 'The import preview shows matched SKUs, Stock Room units, 3PL units, split lines, and unmatched SKUs before adding items to the request.' },
    ],
  },
  {
    version: 'v7.1',
    label: 'Stocktake Move Counts',
    date: '2026-05-14',
    isLatest: false,
    summary: 'Mixed pending scan counts can now be moved between Stock Room stocktake and 3PL send back drafts.',
    changes: [
      { category: 'Inventory', text: 'Pending Scan Count rows now include Move to 3PL or Move to Stock Room, depending on the current counting purpose.' },
      { category: 'Inventory', text: 'Moved rows are removed from the current session and saved into a separate portal draft for the other counting purpose.' },
      { category: 'UI/UX', text: 'This lets staff clean up mixed scan sessions without re-scanning items.' },
    ],
  },
  {
    version: 'v7.0',
    label: 'Stocktake Finalise Rules',
    date: '2026-05-14',
    isLatest: false,
    summary: 'Stock Room stocktake and 3PL send back now stay separate, with full stocktake finalise replacing Stock Room quantities.',
    changes: [
      { category: 'Inventory', text: 'Saved Scan Count drafts are now separated by counting purpose, so Stock Room stocktake sessions and 3PL send back sessions do not appear together.' },
      { category: 'Inventory', text: 'Office stocktake finalise now treats the session as the new Stock Room count: counted SKUs become their counted quantities and uncounted Stock Room SKUs are set to zero.' },
      { category: 'Inventory', text: 'Added a guarded Zero Stock Room action for starting a full office stocktake from zero.' },
      { category: 'UI/UX', text: 'Switching counting purpose now starts a separate scan screen to prevent accidentally mixing Stock Room counts with 3PL send back counts.' },
    ],
  },
  {
    version: 'v6.9',
    label: 'Shared Stocktake Sessions',
    date: '2026-05-14',
    isLatest: false,
    summary: 'Saved Scan Count sessions are now stored in the portal so they can be resumed and corrected from another device.',
    changes: [
      { category: 'Inventory', text: 'Save Session now writes scan counts to the portal as a shared draft, allowing an iPhone scan session to be resumed on a MacBook.' },
      { category: 'Inventory', text: 'Resumed shared sessions keep the same session identity, so edits can be saved back over the same portal draft before finalising.' },
      { category: 'UI/UX', text: 'Local device save remains as a fallback if Wi-Fi is patchy, while successful shared saves now confirm that the session was saved to the portal.' },
    ],
  },
  {
    version: 'v6.8',
    label: 'Stocktake Count Corrections',
    date: '2026-05-14',
    isLatest: false,
    summary: 'Pending Scan Count totals can now be corrected or removed before finalising.',
    changes: [
      { category: 'Inventory', text: 'Added Edit Count controls to pending Scan Count totals so staff can correct a mistaken quantity before Finalise.' },
      { category: 'Inventory', text: 'Added Remove controls for clearing an incorrect SKU from the current scan session.' },
      { category: 'UI/UX', text: 'Pending count quantities are now tappable, giving iPhone users a faster way to correct count mistakes.' },
    ],
  },
  {
    version: 'v6.7',
    label: 'Stocktake Unknown Barcode Fix',
    date: '2026-05-14',
    isLatest: false,
    summary: 'Scan Count now lets staff add an unknown barcode to Stock Room directly from the scanner before counting it.',
    changes: [
      { category: 'Inventory', text: 'Unknown scanned barcodes now show inline SKU and product name fields so staff can add the item to Stock Room without leaving Scan Count.' },
      { category: 'Inventory', text: 'After an unknown barcode is added, the selected item becomes countable immediately and the Add Count button is enabled.' },
      { category: 'UI/UX', text: 'Fixed scanner review messaging so barcodes missing from the barcode list are no longer shown as known barcodes from the master list.' },
    ],
  },
  {
    version: 'v6.6',
    label: 'Stocktake Missing SKU Add',
    date: '2026-05-14',
    isLatest: false,
    summary: 'Scan Count now makes it clear when a barcode is recognised but the SKU is missing from Stock Room, with a direct add action.',
    changes: [
      { category: 'Inventory', text: 'Known barcodes that are not yet in Stock Room now show a prominent Add SKU to Stock Room action using the SKU and product name from the master barcode list.' },
      { category: 'Inventory', text: 'The add action creates the Stock Room item at quantity 0 so staff can count it properly before finalising the session.' },
      { category: 'UI/UX', text: 'Selected SKU and pending count review cards now explain the missing Stock Room item clearly instead of making it look like an unknown barcode.' },
    ],
  },
  {
    version: 'v6.5',
    label: '3PL XLS Export',
    date: '2026-05-14',
    isLatest: false,
    summary: 'Send back to 3PL scan sessions can now export an Excel-compatible receiving file in the required 3PL format.',
    changes: [
      { category: 'Inventory', text: 'Added a 3PL XLS export for Send back to 3PL scan sessions using Item Code, Description, Barcode, Ordered Quantity, Received Quantity, Short / [Excess], and New / Existing Item columns.' },
      { category: 'Inventory', text: 'The 3PL export maps SKU to Item Code, product name to Description, barcode to Barcode, and the scanned total to Ordered Quantity.' },
      { category: 'UI/UX', text: '3PL XLS export appears only in Send back to 3PL mode so office stocktake exports stay simple.' },
    ],
  },
  {
    version: 'v6.4',
    label: 'Stocktake Saved Sessions',
    date: '2026-05-14',
    isLatest: false,
    summary: 'Scan Count sessions can now be saved and resumed on the same device if stocktake is interrupted.',
    changes: [
      { category: 'Inventory', text: 'Added a visible Save Session action to Scan Count so staff can deliberately save their current scan work before stepping away.' },
      { category: 'Inventory', text: 'Saved scan sessions store the counting purpose, counter name, location/bin, and scan rows on the device for later resume.' },
      { category: 'UI/UX', text: 'Scan Count now shows saved session drafts and the last saved time, making the existing device autosave behaviour visible and easier to trust.' },
    ],
  },
  {
    version: 'v6.3',
    label: 'Stocktake Scan Purpose',
    date: '2026-05-14',
    isLatest: false,
    summary: 'Scan Count can now be used either for office stocktake or for counting stock being sent back to 3PL.',
    changes: [
      { category: 'Inventory', text: 'Scan Count now includes a Counting purpose selector with Office stocktake and Send back to 3PL options.' },
      { category: 'Inventory', text: 'Office stocktake keeps the existing behaviour: Finalise updates Stock Room to the counted quantity for counted SKUs.' },
      { category: 'Inventory', text: 'Send back to 3PL finalises counted units as an outbound Sent to 3PL stock movement, deducting the counted quantities from Stock Room.' },
      { category: 'UI/UX', text: 'Scan Count labels, pending count copy, finalise action, and CSV export filename now reflect the selected counting purpose.' },
    ],
  },
  {
    version: 'v6.2',
    label: 'Stocktake Mode Visibility',
    date: '2026-05-13',
    isLatest: false,
    summary: 'Stock Room now clearly shows both Scan Count and Manual Count stocktake entry points.',
    changes: [
      { category: 'Inventory', text: 'Stock Room header now separates Scan Count from Manual Count so the original stocktake workflow is easy to find.' },
      { category: 'UI/UX', text: 'Renamed the secondary stocktake action from Review to Manual Count to make the mode clearer.' },
    ],
  },
  {
    version: 'v6.1',
    label: 'Admin Navigation Panels',
    date: '2026-05-13',
    isLatest: false,
    summary: 'Admin grouped navigation now uses visible section panels instead of a horizontally scrolling tab strip.',
    changes: [
      { category: 'Admin', text: 'Catalogue, Team, and Portal admin sections now appear as separate panels so every setting area is visible without horizontal scrolling.' },
      { category: 'UI/UX', text: 'Admin navigation now wraps cleanly across desktop and smaller screens while keeping the grouped structure.' },
    ],
  },
  {
    version: 'v6.0',
    label: 'Admin Grouped Tabs',
    date: '2026-05-13',
    isLatest: false,
    summary: 'Admin settings now groups tabs into Catalogue, Team, and Portal sections for cleaner navigation.',
    changes: [
      { category: 'Admin', text: 'Admin tabs are now grouped into Catalogue, Team, and Portal so settings are easier to scan.' },
      { category: 'UI/UX', text: 'Updated the Admin subtitle and tab styling to avoid cramped two-line labels and make the page feel more organised.' },
    ],
  },
  {
    version: 'v5.9',
    label: 'Commslayer Conversation Diagnostics',
    date: '2026-05-13',
    isLatest: false,
    summary: 'Commslayer health checks now try multiple conversation endpoint variants so we can identify the working ticket access path instead of relying on one request shape.',
    changes: [
      { category: 'Admin', text: 'Integration Health now tests conversations with bearer auth, api_access_token auth, page parameters, and account_id variants, then reports the first working combination.' },
      { category: 'Dashboard', text: 'Today’s Activity now also tries account_id conversation variants before falling back to the Commslayer unassigned queue link.' },
    ],
  },
  {
    version: 'v5.8',
    label: 'Commslayer Health Filter Fix',
    date: '2026-05-13',
    isLatest: false,
    summary: 'Commslayer health checks now avoid server-side conversation filters that can trigger API errors, then inspect open/unassigned records inside the portal.',
    changes: [
      { category: 'Admin', text: 'Integration Health now calls the documented conversations endpoint without risky status filters, preventing Commslayer 500 errors from simple health checks.' },
      { category: 'Dashboard', text: 'Today’s Activity now fetches conversations first and locally detects open unassigned records for FRT drill-down.' },
    ],
  },
  {
    version: 'v5.7',
    label: 'Integration Health',
    date: '2026-05-13',
    isLatest: false,
    summary: 'Admin now has an Integration Health view for checking Google Sheets, Supabase, and Commslayer connectivity from inside the portal.',
    changes: [
      { category: 'Admin', text: 'Added an Admin > Health tab with Connected, Partial, Broken, and Not configured states for each integration.' },
      { category: 'Admin', text: 'Google Sheets health now checks cases, products, manufacturers, fault types, and claims.' },
      { category: 'Admin', text: 'Supabase and Commslayer health now show reachable tables/endpoints, response timing, and plain-language error details.' },
    ],
  },
  {
    version: 'v5.6',
    label: 'Commslayer Ticket Endpoint',
    date: '2026-05-13',
    isLatest: false,
    summary: 'Commslayer ticket drill-down now targets the documented Integration API conversation endpoint for unassigned ticket visibility.',
    changes: [
      { category: 'Dashboard', text: 'Today’s Activity now tries the documented GET /conversations integration endpoint first when loading unassigned Commslayer tickets.' },
      { category: 'Dashboard', text: 'The Commslayer API base URL is now normalised, so the portal works whether the environment uses the app root or the full /api/integration/v1 endpoint.' },
    ],
  },
  {
    version: 'v5.5',
    label: 'Replenishment Insights',
    date: '2026-05-13',
    isLatest: false,
    summary: 'Replenishment now has a clearer Insights view focused on popup demand, top products, request volume, and follow-up risk.',
    changes: [
      { category: 'Replenishment', text: 'Added a List / Insights toggle to Replenishment so staff can switch from the request table to popup demand analytics.' },
      { category: 'Replenishment', text: 'Insights now splits Adelaide Popup and Sydney Store demand, showing request count, total units, average units per request, top requested products, top requesters, and open ageing.' },
      { category: 'UI/UX', text: 'Added a Key takeaways section with plain-language interpretation for demand split, average request size, most requested product, and ageing requests that need follow-up.' },
    ],
  },
  {
    version: 'v5.4',
    label: 'Retail Order Quick Edits',
    date: '2026-05-12',
    isLatest: false,
    summary: 'Retail Orders can now be updated directly from the list for faster fulfilment tracking.',
    changes: [
      { category: 'Orders', text: 'Retail Orders now supports inline status changes from the list view, so staff can move orders through Pending, Processing, Picked, Packed, Shipped, Delivered, Exception, or Cancelled without opening the order.' },
      { category: 'Orders', text: 'Tracking number, carrier, and estimated delivery date can now be edited directly in the Retail Orders table.' },
    ],
  },
  {
    version: 'v5.3',
    label: 'Manual Stocktake Finder',
    date: '2026-05-12',
    isLatest: false,
    summary: 'Scan Count now makes manual item lookup more prominent, with last barcode digit guidance kept visible for new staff.',
    changes: [
      { category: 'Inventory', text: 'Scan Count now places Find item manually above Count Mode so staff can quickly search by barcode digits, SKU, or product when the camera struggles.' },
      { category: 'UI/UX', text: 'The iPhone guidance for typing the last 4-6 barcode digits remains visible directly under the manual finder input.' },
    ],
  },
  {
    version: 'v5.2',
    label: 'Stock Room Action Groups',
    date: '2026-05-12',
    isLatest: false,
    summary: 'Stock Room actions are now grouped so stocktake/counting is visually separate from day-to-day receive and dispatch movements.',
    changes: [
      { category: 'Inventory', text: 'Stock Room now separates Stocktake actions from Stock Movement actions in the page header to reduce accidental workflow mix-ups.' },
      { category: 'UI/UX', text: 'The mobile Stock Room controls now show Stocktake first, with Receive and Dispatch grouped separately below it.' },
    ],
  },
  {
    version: 'v5.1',
    label: 'Return Label Shortcut',
    date: '2026-05-12',
    isLatest: false,
    summary: 'Return requests now include a direct Starshipit shortcut while keeping the Starshipit order number field clear for reference.',
    changes: [
      { category: 'Returns', text: 'Log Return Request now has an Open Starshipit shortcut for creating prepaid return labels from the submission drawer.' },
      { category: 'Returns', text: 'The Starshipit order number remains a separate reference field so staff can record the generated label/order number cleanly after creating it.' },
    ],
  },
  {
    version: 'v5.0',
    label: 'Stocktake Scanner',
    date: '2026-05-12',
    isLatest: false,
    summary: 'Stock Room now has a mobile Scan Count mode for barcode-based stocktake with local scan history, manual fallback, running totals, and CSV export.',
    changes: [
      { category: 'Inventory', text: 'Scan Count — Stock Room now includes a mobile-first barcode scanning mode for stocktake, designed for iPhone cameras and fast physical counting.' },
      { category: 'Inventory', text: 'Barcode matching — the SNAP master barcode list has been extracted into the portal so scans can match barcode to SKU and product name.' },
      { category: 'Inventory', text: 'Counting safeguards — scan sessions include duplicate scan pause, unknown barcode warnings, undo last scan, vibration/sound feedback where supported, and manual barcode entry fallback.' },
      { category: 'UI/UX', text: 'Scan feedback now uses an in-camera confirmation card and green/amber/red scanner flash instead of relying on an audible beep, making successful counts easier to see during stocktake.' },
      { category: 'UI/UX', text: 'Stock Room and Stocktake screens now use a phone/tablet-friendly layout with a prominent mobile scan entry point, larger inputs, single-column scanning flow, and sticky phone actions for undo, export, and exit.' },
      { category: 'Inventory', text: 'Fallback search now accepts last barcode digits, SKU, or product name with tap-to-count results, plus numeric keyboard support on iPhone for digit entry.' },
      { category: 'Inventory', text: 'Camera scan controls now include clearer scan guidance, a reset camera action, and a torch button on devices that expose flashlight support.' },
      { category: 'Inventory', text: 'Scan Count now defaults to Batch Count mode: scan one item to identify the SKU, enter the physical quantity counted, and add it as a pending stocktake count instead of scanning every unit.' },
      { category: 'UI/UX', text: 'Selected SKU quantity entry now has large − / + stepper controls with press-and-hold repeat, while keeping Add Count as the deliberate commit action.' },
      { category: 'Inventory', text: 'Known scanned barcodes that are missing from Stock Room can now be added directly from the stocktake flow using the barcode master product name and SKU, with quantity starting at 0.' },
      { category: 'Inventory', text: 'Pending scan counts do not change Stock Room live; Finalise applies Stocktake Adjustment movements for counted SKUs only after confirmation.' },
      { category: 'Inventory', text: 'Offline-friendly export — scans are saved locally on the device during the session and can be exported to CSV with counter and location/bin details for end-of-count review.' },
    ],
  },
  {
    version: 'v4.5',
    label: 'FRT Status States',
    date: '2026-05-08',
    isLatest: false,
    summary: 'Commslayer first response time now has clear green, amber, and red dashboard states with positive reinforcement when the team is ahead.',
    changes: [
      { category: 'Dashboard', text: 'FRT under 24 hours now shows a green Great pace state with a short kudos message for the team.' },
      { category: 'Dashboard', text: 'FRT between 24 and 48 hours now shows an amber Within target state so it feels acceptable but watchful.' },
      { category: 'Dashboard', text: 'FRT over 48 hours remains a red breach with the Commslayer unassigned queue action.' },
    ],
  },
  {
    version: 'v4.4',
    label: 'Live FRT Breach Timer',
    date: '2026-05-08',
    isLatest: false,
    summary: 'The Commslayer FRT breach alert now shows a live over-breach timer so the team can see how long the queue has been past the 48-hour limit.',
    changes: [
      { category: 'Dashboard', text: 'FRT breach alerts now show how long the current average first response time is over the 48-hour maximum.' },
      { category: 'Dashboard', text: 'The FRT time updates while the dashboard is open, using the latest Commslayer fetch as the starting point until the next refresh.' },
    ],
  },
  {
    version: 'v4.3',
    label: 'FRT Alert Polish',
    date: '2026-05-08',
    isLatest: false,
    summary: 'The Commslayer FRT breach alert is now clearer and more urgent without adding a distracting scrolling banner.',
    changes: [
      { category: 'Dashboard', text: 'FRT breach wording now calls out unassigned first replies so the action is clearer for the team.' },
      { category: 'Dashboard', text: 'The alert now shows Current vs Max timing and how far over the 48-hour limit the queue is.' },
      { category: 'UI/UX', text: 'The breach indicator now uses a stronger pulsing red dot and slightly firmer red treatment while keeping the dashboard calm enough to work from.' },
    ],
  },
  {
    version: 'v4.2',
    label: 'Promotion End Fix',
    date: '2026-05-08',
    isLatest: false,
    summary: 'Ending a promotion now immediately removes it from the dashboard and moves it out of the active promotion list.',
    changes: [
      { category: 'Promotions', text: 'End promotion now disables the promotion as well as setting today as the end date, so it clears from the dashboard immediately.' },
      { category: 'Promotions', text: 'Promotions ended manually are now shown in Archive instead of lingering as active or paused for the rest of the day.' },
    ],
  },
  {
    version: 'v4.1',
    label: 'Commslayer Queue Fallback',
    date: '2026-05-08',
    isLatest: false,
    summary: 'FRT breach alerts now include a direct Commslayer unassigned queue link when ticket-level drill-down is unavailable.',
    changes: [
      { category: 'Dashboard', text: 'FRT breach alerts now show an Open Unassigned in Commslayer button when the API cannot return individual tickets.' },
      { category: 'Dashboard', text: 'Removed the raw Commslayer API diagnostic from the team-facing dashboard so the alert stays operational and clear.' },
    ],
  },
  {
    version: 'v4.0',
    label: 'FRT Ticket Drill-down',
    date: '2026-05-08',
    isLatest: false,
    summary: 'Commslayer FRT alerts can now show the oldest unassigned tickets with direct links into Commslayer when conversation-read access is available.',
    changes: [
      { category: 'Dashboard', text: 'FRT breach banners now list the oldest unassigned tickets when the Commslayer token can read conversations.' },
      { category: 'Dashboard', text: 'Each listed ticket links directly to the matching Commslayer conversation so the team can work the breach oldest-first.' },
      { category: 'Performance', text: 'If live ticket access is missing, the dashboard now explains that conversation/message read permissions are required for drill-down.' },
    ],
  },
  {
    version: 'v3.9',
    label: 'Commslayer FRT Alerts',
    date: '2026-05-08',
    isLatest: false,
    summary: 'Today’s Activity now treats first response time as an operational alert, with a 48-hour maximum and clearer escalation guidance.',
    changes: [
      { category: 'Dashboard', text: 'Avg FRT now uses practical thresholds: green under 24 hours, amber between 24 and 48 hours, and red once it exceeds the 48-hour maximum.' },
      { category: 'Dashboard', text: 'When FRT is amber or red, the activity card now shows a response action banner so the team knows to prioritise first replies.' },
      { category: 'Performance', text: 'Long first response times now show more detail, such as days plus hours, instead of rounding everything down to whole days.' },
    ],
  },
  {
    version: 'v3.8',
    label: 'Roster-Aware Dashboard',
    date: '2026-05-08',
    isLatest: false,
    summary: 'Today’s Team now reflects the actual roster for the day, including overrides and clearer login status.',
    changes: [
      { category: 'Dashboard', text: 'Today’s Team now reads today’s roster overrides, so people manually rostered on or off are shown correctly on the dashboard.' },
      { category: 'Dashboard', text: 'Scheduled team members who have not logged in are now highlighted clearly instead of appearing as a muted note.' },
      { category: 'Roster', text: 'Leave and override context is carried into the dashboard strip, making today’s coverage easier to scan without opening the roster.' },
    ],
  },
  {
    version: 'v3.7',
    label: 'Portal QOL Links',
    date: '2026-05-07',
    isLatest: false,
    summary: 'Order numbers are now more connected across the portal, with recent order recall, timeline links, and smoother pre-filled actions from customer-care history.',
    changes: [
      { category: 'Orders', text: 'Recent orders — the command menu now remembers recently viewed order timelines so you can reopen customer context quickly.' },
      { category: 'Orders', text: 'Timeline deep links — return details, refund rows, and timeline quick actions now link back into the unified Order Timeline.' },
      { category: 'Refunds', text: 'Prefilled refund requests — starting a refund from an order timeline now carries the order number into the refund form.' },
      { category: 'Cases', text: 'Prefilled fault cases — starting a fault case from an order timeline now carries the order number into the case form.' },
      { category: 'Returns', text: 'Sticky office return save bar — the Process Office Return form keeps Cancel and Save visible while you work through longer returns.' },
    ],
  },
  {
    version: 'v3.6',
    label: 'Order Timeline',
    date: '2026-05-07',
    isLatest: false,
    summary: 'Order Lookup is now a unified timeline that combines fault cases, returns, refunds, summary status, and quick actions in one customer-care view.',
    changes: [
      { category: 'Orders', text: 'Unified timeline — searching an order now shows cases, return records, and refund requests in one chronological history.' },
      { category: 'Orders', text: 'Status summary — order results now surface high-level chips like Awaiting Customer, Follow-up Required, Refund Pending, Fault Case Open, or All Closed.' },
      { category: 'Orders', text: 'Quick actions — from an order timeline you can jump straight to Log Return Request, Process Office Return, Request Refund, or Submit Fault Case.' },
      { category: 'UI/UX', text: 'Related records panel — cases, returns, and refunds are counted and linked from the same view, reducing repeat searches across separate pages.' },
    ],
  },
  {
    version: 'v3.5',
    label: 'Command Menu',
    date: '2026-05-07',
    isLatest: false,
    summary: 'The header search is now a global command menu with quick actions, page jumps, and unified record search from anywhere in the portal.',
    changes: [
      { category: 'UI/UX', text: 'Command menu — click the header search or press ⌘K / Ctrl+K to open a portal-wide launcher.' },
      { category: 'UI/UX', text: 'Quick actions — start common workflows directly, including Log Return Request, Process Office Return, Request Refund, Submit Fault Case, and Lookup Order. Sidebar hints show the fastest ⌘K letter shortcuts for the main actions.' },
      { category: 'UI/UX', text: 'Page jumps — type a page name such as Returns, Stock Room, Roster, or Admin to navigate without using the sidebar.' },
      { category: 'UI/UX', text: 'Unified results — typing an order, customer, product, or fault detail still searches cases, refunds, and returns in the same menu.' },
    ],
  },
  {
    version: 'v3.4',
    label: 'Returns Workflow Cleanup',
    date: '2026-05-07',
    isLatest: false,
    summary: 'Returns now match the real office workflow: requests stay in Awaiting Customer until the parcel is processed, and follow-ups only appear when deliberately marked.',
    changes: [
      { category: 'Returns', text: 'Awaiting Customer queue — return requests now stay in one clear holding area until the parcel is processed in the office. The old Ready to Process / Parcel Arrived middle step has been removed.' },
      { category: 'Returns', text: 'Direct processing — each awaiting return now has a Process Return action that opens the office processing form pre-filled from the request.' },
      { category: 'Returns', text: 'Office processing form — Log Return has been renamed to Process Office Return, with linked request context kept visible while processing.' },
      { category: 'Returns', text: 'Follow-up Required — follow-ups are now an intentional bucket based only on returns explicitly marked for follow-up, not on how long a customer has been waiting to send a parcel.' },
      { category: 'Returns', text: 'Closed by default — processed office returns close automatically unless follow-up is required. Follow-up owner and notes only appear when that option is selected.' },
    ],
  },
  {
    version: 'v3.3',
    label: 'Stocktake Mode',
    date: '2026-05-07',
    isLatest: false,
    summary: 'A dedicated Stocktake Mode on the Stock Room page makes counting inventory faster — work through products with a keyboard, track progress, and save all changes at once.',
    changes: [
      { category: 'Inventory', text: 'Stocktake Mode — a new mode replaces the normal table with a clean counting layout: product, SKU, on-hand quantity, a large count input, and a live variance column showing +/− differences.' },
      { category: 'Inventory', text: 'Keyboard-first workflow — Tab or Enter moves between count inputs automatically. Pressing Enter also ticks the row as counted, letting you move through the list without touching the mouse.' },
      { category: 'Inventory', text: 'Progress tracking — a progress bar and counter show how many products have been ticked off. A floating save bar appears as soon as changes are entered.' },
      { category: 'Inventory', text: 'Save All — changes are committed in one action as Stocktake Adjustment movements, creating a full audit trail. EOL/discontinued products are shown but excluded from counting.' },
      { category: 'Inventory', text: 'Print Checklist — generates a printable sheet with product name, SKU, current quantity, and blank count/tick boxes for doing a physical count on paper first.' },
    ],
  },
  {
    version: 'v3.2',
    label: 'Returns Form QOL',
    date: '2026-05-07',
    isLatest: false,
    summary: 'Logging returns is now faster — auto-fill from return requests includes product items, fee deductions calculate live, and a success screen lets you log the next return without navigating away.',
    changes: [
      { category: 'Returns', text: 'Item auto-population — when a return request is matched by order number, the form now pre-fills the full list of items (product/SKU, condition, decision) logged by the team, not just customer details.' },
      { category: 'Returns', text: 'Delete pre-filled items — if a customer didn\'t send back one of the expected items, you can remove it with the trash icon. The delete button is always visible when items were pulled from a linked request.' },
      { category: 'Returns', text: 'Automatic fee deductions — selecting "Refund - Return Label Fee" deducts $9.50 from the gross amount automatically; "Refund + Restocking Fee" deducts an entered percentage. A live breakdown shows gross, deduction, and net refund before saving.' },
      { category: 'Returns', text: 'Post-submit success screen — after logging a return, instead of redirecting to the list you\'re shown a confirmation with two options: View Returns or Log Another. Your "Processed By" name is remembered so you don\'t have to re-enter it.' },
    ],
  },
  {
    version: 'v3.1',
    label: 'Today\'s Activity on Dashboard',
    date: '2026-05-06',
    isLatest: false,
    summary: 'The dashboard now shows a Today\'s Activity card from Commslayer, surfacing tickets created, tickets closed, average first response time, and messages sent for the current day.',
    changes: [
      { category: 'Dashboard', text: 'Today\'s Activity card — a new card on the dashboard pulls today\'s Commslayer report data: tickets created, tickets closed, average first response time, and total messages sent by the team.' },
      { category: 'Dashboard', text: 'FRT colour coding — the first response time tile turns amber (> 1 hour) or red (> 2 hours) automatically, so a slow response day is immediately visible.' },
      { category: 'Dashboard', text: 'Non-fatal integration — if Commslayer is unreachable or not configured the card simply doesn\'t appear, so the rest of the dashboard is never affected.' },
    ],
  },
  {
    version: 'v3.0',
    label: 'Daily Performance View',
    date: '2026-05-06',
    isLatest: false,
    summary: 'Team Performance now supports a daily view, letting you check individual agent output for any specific day.',
    changes: [
      { category: 'Performance', text: 'Daily view — a new Day toggle sits alongside Month and Week on the Team Performance page. Step through individual days using the arrows, or jump straight back to Today with the shortcut button.' },
      { category: 'Performance', text: 'Day-accurate scorecard — in Day mode, the agent scorecard shows replies sent that specific day against the daily KPI target, so you can see at a glance whether each agent is on track.' },
      { category: 'Performance', text: 'Smart defaults — the page now defaults to Week view (more practical for day-to-day monitoring), and charts are hidden in Day mode since a single-day bar chart adds no value.' },
    ],
  },
  {
    version: 'v2.9',
    label: 'Cross-linking & Session Fixes',
    date: '2026-05-06',
    isLatest: false,
    summary: 'Refund requests now auto-link to their matching return record, the Submit Fault page correctly auto-fills your name, and the Returns page opens directly to a filtered order when linked from Refunds.',
    changes: [
      { category: 'Refunds', text: 'Return cross-link — the Refund Requests page now fetches return records on load and displays a "Return" badge on any refund whose order number matches an existing return entry. Clicking it takes you directly to that return\'s detail page.' },
      { category: 'Returns', text: 'Deep-link by order number — navigating to /returns?order=XXXXX now pre-fills the search and switches to the Requested tab automatically, so the linked return is immediately visible.' },
      { category: 'Cases', text: 'Submit Fault name auto-fill — the "Submitted By" field on the Submit Fault page now reads directly from your login session instead of form state, fixing the bug where names showed as "—" and prevented submission.' },
    ],
  },
  {
    version: 'v2.8',
    label: 'UI Speed & Clarity',
    date: '2026-05-05',
    isLatest: false,
    summary: 'Faster triage with inline status changes, a leaner cases table, keyboard search shortcut, and a cleaner sidebar.',
    changes: [
      { category: 'Cases', text: 'Inline status change — click any status badge directly in the Cases list to change it (e.g. Pending → Approved) without opening the detail page. Saves time during bulk admin triage.' },
      { category: 'Cases', text: 'Claim status column — a new Status column now appears in the Cases table between Fault Type and Cost, so status is visible at a glance without opening each case.' },
      { category: 'Cases', text: 'Table column cleanup — removed Manufacturer, Submitted By, Evidence and the edit pencil from the Cases table. The table is now 8 focused columns instead of 11.' },
      { category: 'UI/UX', text: '⌘K search shortcut — press ⌘K (or Ctrl+K on Windows) anywhere in the portal to instantly focus the header search bar.' },
      { category: 'UI/UX', text: 'Header breadcrumb — the header now shows your current location in the portal (e.g. Operations › All Cases) so it\'s always clear where you are.' },
      { category: 'UI/UX', text: 'Sidebar Quick Actions block — Submit Fault, Log Return, and Request Refund are now pinned as a highlighted Quick Actions block at the top of the sidebar for one-click access.' },
      { category: 'UI/UX', text: 'Sidebar consolidation — sidebar navigation reduced from 7 groups to 4 (Operations, Inventory, Team, System), making it easier to scan and reducing visual noise.' },
    ],
  },
  {
    version: 'v2.7',
    label: 'Annual Leave Payout',
    date: '2026-05-05',
    isLatest: false,
    summary: 'Staff can now request payout of unused annual leave days after their anniversary, with admin approve/deny workflow.',
    changes: [
      { category: 'Roster', text: 'Annual leave payout requests — staff can request unused annual leave days to be paid out once their anniversary date is reached. Whole days only (e.g. 1, 2, 3) — partial days are not permitted.' },
      { category: 'Roster', text: 'Admin review workflow — pending payout requests are flagged directly on each agent\'s annual leave balance card with Approve and Deny buttons. No extra page needed.' },
      { category: 'Roster', text: 'Admin alert banner — when any payout request is pending review, an amber banner appears at the top of the Leave Log page so nothing goes unnoticed.' },
      { category: 'Roster', text: 'Balance accuracy — approved payout days are automatically deducted from the displayed annual leave balance, so totals always reflect reality.' },
    ],
  },
  {
    version: 'v2.6',
    label: 'Layout Polish',
    date: '2026-05-05',
    isLatest: false,
    summary: 'Case detail two-column layout and admin tab bar scrolling on small screens.',
    changes: [
      { category: 'Cases', text: 'Case detail view — Case Info and Product Info fields now display in a two-column grid, reducing vertical scrolling and making better use of horizontal screen space.' },
      { category: 'Admin', text: 'Admin tab bar — now scrolls horizontally on small screens instead of overflowing. All 8 tabs remain accessible regardless of window size.' },
    ],
  },
  {
    version: 'v2.5',
    label: 'My Submissions & Filters',
    date: '2026-05-05',
    isLatest: false,
    summary: 'Mine filter on Cases, Returns, and Refunds — plus date presets and search on Refunds.',
    changes: [
      { category: 'Cases',   text: '"Mine" toggle button — filter All Cases to show only cases you submitted, with a single click. Active state is highlighted in brand blue.' },
      { category: 'Cases',   text: 'Date presets on Cases filter panel — Today, This Week, This Month, and Last 30 Days quick-select buttons above the date range inputs.' },
      { category: 'Returns', text: '"Mine" toggle on both Requested and Processed tabs — filters to returns you logged (by submitter name).' },
      { category: 'Returns', text: 'Week quick-jump buttons on Processed tab — Last Week, 2 Weeks Ago, 3 Weeks Ago and a "↩ This Week" shortcut when viewing a past week.' },
      { category: 'Refunds', text: '"Mine" toggle on Refunds — filter the queue to refunds you submitted.' },
      { category: 'Refunds', text: 'Search on Refunds — search by order number or customer name; expandable panel with Today/This Week/Last 30d date presets and a manual date range picker.' },
    ],
  },
  {
    version: 'v2.4',
    label: 'CC&E SOP',
    date: '2026-05-05',
    isLatest: false,
    summary: 'CC&E Standard Operating Procedure built into the portal — all 13 sections, searchable and always accessible from the sidebar.',
    changes: [
      { category: 'UI/UX', text: 'CC&E SOP page — full Standard Operating Procedure (v1.4) now lives in the portal under Resources → CC&E SOP, with sticky table of contents, section callouts, tables, and checklists' },
      { category: 'UI/UX', text: 'Admin-only edit controls coming in a future release — content can be updated via the source file in the meantime' },
    ],
  },
  {
    version: 'v2.3',
    label: 'Bug Fixes & Roster',
    date: '2026-05-05',
    isLatest: false,
    summary: 'Today\'s Team dashboard strip, roster monthly rotation, timezone fix, and refund form fixes.',
    changes: [
      { category: 'Dashboard', text: 'Today\'s Team strip — shows who\'s scheduled today with a green dot indicator for anyone already signed into the portal' },
      { category: 'Returns', text: 'Fixed missing returns — API was silently capping results to 1 record when no limit param was passed' },
      { category: 'Refunds', text: 'US orders: $9.50 return label fee auto-deducted from refund amount by default — checkbox to waive if offering free returns' },
      { category: 'Refunds', text: 'AU orders: optional $9.50 prepaid return label fee checkbox — tick to deduct when a label was provided, leave unticked if customer covered their own postage' },
      { category: 'Roster', text: 'Monthly rotation — Gail and Niko swap days off each month; rotation anchors to Monday if the 1st falls mid-week' },
      { category: 'Roster', text: 'Fixed straddle-week bug — weeks spanning two months now consistently use the Monday\'s month for phase lookup, preventing 6-day overwork alerts' },
      { category: 'Admin', text: 'Login history now groups by ACST/ACDT (Australia/Adelaide) date — logins no longer appear under "Yesterday" when made in the morning' },
      { category: 'Refunds', text: 'Fixed "Please select your name" error for staff submitting refund requests — name now resolved from session at submit time' },
      { category: 'Refunds', text: 'Processed By field now auto-fills from the logged-in user\'s session — dropdown removed' },
      { category: 'UI/UX', text: 'What\'s New modal — pops up on the dashboard when a new version is released, showing a summary of changes with category tags; dismisses to localStorage so it only appears once per release' },
    ],
  },
  {
    version: 'v2.2',
    label: 'Internal Notes',
    date: '2026-05-03',
    isLatest: false,
    summary: 'Append-only internal notes on fault cases, returns, and refund requests.',
    changes: [
      { category: 'Cases', text: 'Internal notes panel on case detail pages — timestamped, author-attributed, append-only thread with ⌘↵ shortcut' },
      { category: 'Returns', text: 'Internal notes panel on return detail pages — same timeline component as cases' },
      { category: 'Refunds', text: 'Notes button on each refund row — opens a modal with the full notes thread; badge shows note count when notes exist' },
      { category: 'UI/UX', text: 'Shared InternalNotes component with coloured author avatars, relative timestamps, and a textarea composer' },
      { category: 'Admin', text: 'Notes stored as JSON on Google Sheets (cases, col O) and Supabase JSONB (returns + refund_requests)' },
    ],
  },
  {
    version: 'v2.1',
    label: 'Claim Outcomes & Recovery Tracking',
    date: '2026-05-03',
    isLatest: false,
    summary: 'Manufacturer claim outcomes with partial credit support, recovery rate summary, and outcome detail modal.',
    changes: [
      { category: 'Cases', text: 'New "Partial Credit" claim status — for when a manufacturer approves only a portion of a claim batch' },
      { category: 'Cases', text: 'Record Outcome modal — triggered when marking a claim as Credit Received, Partial Credit, or Rejected; captures amount recovered, outcome date, and notes' },
      { category: 'Cases', text: 'Recovery Summary strip on the Claims page — shows total at risk, total recovered, open exposure, and recovery rate % with progress bar' },
      { category: 'Cases', text: 'Per-manufacturer recovery totals shown in each section header (at risk vs recovered)' },
      { category: 'Cases', text: 'Outcome detail row — expand any resolved claim to see outcome date, status badge, and notes inline in the table' },
      { category: 'Cases', text: 'Amount Recovered column added to claims table — shows recovered amount for settled claims, "pending" for open ones' },
    ],
  },
  {
    version: 'v2.0',
    label: 'Login History & Promotions UI',
    date: '2026-05-03',
    isLatest: false,
    summary: 'Staff login timeline in Admin and promotions strip redesigned to match portal UI.',
    changes: [
      { category: 'Admin', text: 'Login History feed in Admin > Logins — groups clock-in events by day (Today / Yesterday / date) with coloured initials, role badge, and relative time' },
      { category: 'Admin', text: 'Filter by staff member and date range (7 / 14 / 30 days) — fetches from shift_logs via new /api/admin/login-history endpoint' },
      { category: 'Promotions', text: 'Active Promotions strip rebuilt as a portal-native card — replace letterboard / scramble ticker with clean divide-y rows, store badges, discount chips, and countdown pills' },
      { category: 'Promotions', text: 'Major Sale Banner redesigned as an amber-bordered card with sale name, discount badge, code chip, store badge, dates, and days-left countdown' },
    ],
  },
  {
    version: 'v1.9',
    label: 'Dashboard Redesign & Navigation',
    date: '2026-05-03',
    isLatest: false,
    summary: 'Full dashboard overhaul, returns navigation restructure, and an Admin changelog tab.',
    changes: [
      { category: 'Dashboard', text: 'Complete dashboard rebuild — replaced cluttered stat cards with a compact 4-cell QuickStat strip (Faults This Week, Cost at Risk, Awaiting Parcel, Follow-ups Due)' },
      { category: 'Dashboard', text: 'Weekly Fault Chart (2/3 width) sits alongside AI Briefing or Today\'s Activity (1/3 width) in a two-column mid-section' },
      { category: 'Dashboard', text: 'Recent Cases table (2/3) shown beside Today\'s Activity feed (1/3) for admin users' },
      { category: 'Dashboard', text: 'By Manufacturer and By Fault Type breakdown panels use inline bar lines — no heavy charts, loads instantly' },
      { category: 'Dashboard', text: 'Returns summary row shows 3 numbers side by side: returns this week, amount refunded, and pending follow-ups' },
      { category: 'Dashboard', text: 'Replenishment summary row (admin only) shows pending orders, in-transit count, and tracking alerts' },
      { category: 'Dashboard', text: 'Promotions strip and Major Sale banner moved to the bottom of the dashboard' },
      { category: 'Returns', text: '"Log Return Request" moved to the sidebar as a teal action link — consistent with Submit Fault and Request Refund' },
      { category: 'Returns', text: 'Removed duplicate Log Request / Log Return button from page header; secondary Log Return button kept on Processed tab' },
      { category: 'Admin', text: 'New Changelog tab in Admin — full version history accordion with category colour badges, dates, and change counts' },
      { category: 'Admin', text: '"New" badge appears on the Admin sidebar link whenever a version has been released since the user last visited the Changelog tab' },
    ],
  },
  {
    version: 'v1.8',
    label: 'UI Polish',
    date: '2026-05-03',
    isLatest: false,
    summary: 'Visual refinements across the portal — sidebar, tables, dashboard, and loading states.',
    changes: [
      { category: 'UI/UX', text: 'Sidebar active nav item now shows a soft blue tint with an inset left-border accent instead of a filled block' },
      { category: 'UI/UX', text: 'Active nav icon tints brand-300; label goes semibold for stronger legibility' },
      { category: 'Dashboard', text: 'Week-over-week ↑↓ delta pills added to KPI stat cards — green for improvement, red for increase (more faults/cost = worse)' },
      { category: 'Dashboard', text: 'Section zones: Returns, Replenishment, and AI Briefing areas each sit inside a subtly gradient-tinted container for visual rhythm' },
      { category: 'UI/UX', text: 'Table even rows carry a warm brand tint (#f5fbfd); headers are tighter and more distinct with uppercase wider tracking' },
      { category: 'UI/UX', text: 'Numeric columns across all tables are right-aligned with monospaced tabular figures via .num CSS class' },
      { category: 'UI/UX', text: 'New PageSkeleton and DashboardSkeleton components provide a consistent full-page shimmer on initial load; Claims page updated to use PageSkeleton' },
      { category: 'Promotions', text: 'Upcoming promotions show a sky-blue countdown badge ("in 3d", "tomorrow") in the dashboard strip; promo name dims until live' },
    ],
  },
  {
    version: 'v1.7',
    label: 'Performance & Reliability',
    date: '2026-05-01',
    summary: 'Server-side pagination, in-memory caching, lazy-loading, and hardened error handling.',
    changes: [
      { category: 'Cases', text: 'Cases API now supports server-side filtering, sorting, and pagination — page/limit params, CSV export fetches all matching rows' },
      { category: 'Returns', text: 'Returns API supports server-side search, date range, page, and limit params with Supabase .range() for efficient queries' },
      { category: 'Dashboard', text: 'Dashboard aggregations cached in-memory (60s TTL) to avoid recomputing on every page load' },
      { category: 'Dashboard', text: 'Recharts lazy-loaded via dynamic import — code-split into a separate chunk to reduce initial bundle size' },
      { category: 'UI/UX', text: 'All silent catch blocks replaced with visible error states and console.error/warn logging' },
      { category: 'Admin', text: 'Staff list cached in component state — no longer refetched on every modal open' },
      { category: 'UI/UX', text: 'Shared date/week utility functions extracted to lib/utils.ts to eliminate duplication across pages' },
    ],
  },
  {
    version: 'v1.6',
    label: 'Authentication & Security',
    date: '2026-04-30',
    summary: 'Full staff authentication with role-based access control, password management, and audit logging.',
    changes: [
      { category: 'Security', text: 'Staff login page with session-cookie authentication — bcrypt-hashed passwords, signed SESSION_SECRET' },
      { category: 'Security', text: 'Role-based access control — admin vs. standard staff; admin-only pages and sidebar items gated accordingly' },
      { category: 'Security', text: 'Middleware enforces authentication on all portal routes; redirects unauthenticated users to /login' },
      { category: 'Security', text: 'Change Password page at /account/password — requires current password before updating' },
      { category: 'Admin', text: 'Admin > Logins panel shows all staff with last-login timestamp and role; admins can set/reset passwords' },
      { category: 'Admin', text: 'SESSION_SECRET throws at startup if missing — prevents silent insecure deployments' },
      { category: 'Cases', text: 'Input validation added to cases and refunds API routes — rejects malformed payloads with 400 errors' },
    ],
  },
  {
    version: 'v1.5',
    label: 'Roster & Leave Management',
    date: '2026-04-28',
    summary: 'Full roster calendar with drag-to-override, leave log, public holiday coverage, and iPad support.',
    changes: [
      { category: 'Roster', text: 'Weekly roster calendar showing all staff shifts with colour-coded role bands' },
      { category: 'Roster', text: 'Clickable Today bar navigates directly to the current week\'s view' },
      { category: 'Roster', text: 'Drag-to-override: shift cells can be dragged to swap or reassign staff for the day' },
      { category: 'Roster', text: '5-day staffing alert banner fires when coverage drops below the configured minimum threshold' },
      { category: 'Roster', text: 'Leave Log page — submit, view, approve/deny leave requests with date range and staff filter' },
      { category: 'Roster', text: 'Admin > Roster Settings panel to configure shift patterns, minimum staffing, and public holiday coverage' },
      { category: 'UI/UX', text: 'iPad-responsive sidebar drawer — hamburger menu slides in/out on mobile and tablet viewports' },
      { category: 'UI/UX', text: 'Table overflow and grid layout fixes for sub-1024px screens across all list pages' },
    ],
  },
  {
    version: 'v1.4',
    label: 'Replenishment Module',
    date: '2026-04-25',
    summary: 'End-to-end replenishment order tracking from request through to delivery confirmation.',
    changes: [
      { category: 'Replenishment', text: 'Replenishment list page — view all orders with status badges, supplier, and ETA filters' },
      { category: 'Replenishment', text: 'Replenishment detail page — line-item breakdown with quantity ordered, received, and variance' },
      { category: 'Replenishment', text: 'Skip toggle on line items — mark a line as skipped (won\'t count toward completion)' },
      { category: 'Replenishment', text: 'Mark Delivered button — logs received quantities and updates order status to Delivered' },
      { category: 'Replenishment', text: 'Alert badge on sidebar Replenishment link when orders are overdue' },
      { category: 'Admin', text: 'Supabase migration files for replenishment_orders and replenishment_line_items tables' },
    ],
  },
  {
    version: 'v1.3',
    label: 'Team Performance & AI Briefing',
    date: '2026-04-22',
    summary: 'Team performance dashboard with Commslayer integration and AI-generated daily briefings.',
    changes: [
      { category: 'Performance', text: 'Team Performance page — per-agent metrics (cases handled, avg resolution time, CSAT) with week/month toggle' },
      { category: 'Performance', text: 'Recharts bar and line charts showing trend data over the selected period' },
      { category: 'Performance', text: 'KPI Targets panel in Admin — configure thresholds for resolution time and case volume' },
      { category: 'Dashboard', text: 'AI Briefing card — calls Claude (Haiku) each morning to summarise overnight case activity and surface anomalies' },
      { category: 'Dashboard', text: 'Active Promotions ticker strip on the dashboard homepage — scrolling marquee of live promos' },
      { category: 'Promotions', text: 'Promotions management page — add/edit/deactivate promotions with start/end dates and product associations' },
    ],
  },
  {
    version: 'v1.2',
    label: 'Inventory & Promotions',
    date: '2026-04-18',
    summary: 'Stock room management with discontinued product support and promotions tracking.',
    changes: [
      { category: 'Inventory', text: 'Stock Room page — full inventory list with search, manufacturer filter, and stock level indicators' },
      { category: 'Inventory', text: 'Discontinued flag on products — marks items as discontinued with visual badge; admin can toggle per product' },
      { category: 'Promotions', text: 'Promotions page with active/upcoming/expired tabs and inline add/edit modal' },
      { category: 'Dashboard', text: 'Sticky table headers on all list pages — column labels stay visible when scrolling long tables' },
      { category: 'UI/UX', text: 'Keyboard navigation in header search — arrow keys cycle results, Enter navigates, Escape dismisses' },
      { category: 'UI/UX', text: 'Empty state illustrations with CTA buttons on filtered views with no results' },
    ],
  },
  {
    version: 'v1.1',
    label: 'Customer Module',
    date: '2026-04-14',
    summary: 'Returns processing, refund requests, and order lookup added to the portal.',
    changes: [
      { category: 'Returns', text: 'Returns list page — log and process return requests with status workflow (Requested → Received → Processed → Refunded)' },
      { category: 'Returns', text: 'Alert badge on sidebar Returns link when items have been waiting more than 3 days' },
      { category: 'Refunds', text: 'Refund Requests page — raise, review, and approve/decline refunds with amount and reason tracking' },
      { category: 'Refunds', text: 'Alert badge on sidebar Refunds link showing count of pending refund requests' },
      { category: 'Orders', text: 'Order Lookup page — search by order number or customer name; shows order lines, status, and linked cases' },
      { category: 'Dashboard', text: 'Returns and Refunds KPI cards on the dashboard homepage with weekly counts' },
    ],
  },
  {
    version: 'v1.0',
    label: 'Core Portal',
    date: '2026-04-10',
    summary: 'Initial release — fault case management, claims, and admin configuration.',
    changes: [
      { category: 'Cases', text: 'Fault Cases list — log, search, filter by manufacturer/status/date, and sort all open cases' },
      { category: 'Cases', text: 'Submit Fault form — create a new case with product, manufacturer, fault type, and description' },
      { category: 'Cases', text: 'Case detail page — full case history, status updates, and linked claim' },
      { category: 'Cases', text: 'Claims tab — track manufacturer warranty claims linked to fault cases with status workflow' },
      { category: 'Admin', text: 'Products, Manufacturers, and Fault Types management panels with add/edit/delete' },
      { category: 'Admin', text: 'Staff management — add team members with name, email, and role' },
      { category: 'Dashboard', text: 'Homepage dashboard with case volume KPI cards and weekly trend chart' },
    ],
  },
];

// ─── Helpers ───────────────────────────────────────────────────────────────────

export const LATEST_VERSION = CHANGELOG.find(v => v.isLatest)?.version ?? CHANGELOG[0]?.version;

/** localStorage key used to track which version the user last acknowledged */
export const CHANGELOG_SEEN_KEY = 'portal_changelog_seen';
